"""add slug

Revision ID: bfeffdcea36b
Revises: e2ad78b9ab84
Create Date: 2026-06-22 08:25:37.538823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfeffdcea36b'
down_revision = 'e2ad78b9ab84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_problem_slug'), 'problem', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_slug'), table_name='problem')
    op.drop_column('problem', 'slug')
    # ### end Alembic commands ###
