"""add ai models phase 3

Revision ID: d3b1054978bc
Revises: bfeffdcea36b
Create Date: 2026-06-22 08:34:29.691892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b1054978bc'
down_revision = 'bfeffdcea36b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_analysis_id'), 'problem_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_problem_analysis_problem_id'), 'problem_analysis', ['problem_id'], unique=True)
    op.create_table('problem_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('teacher_data', sa.JSON(), nullable=True),
    sa.Column('similarity_data', sa.JSON(), nullable=True),
    sa.Column('markdown_content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_notes_id'), 'problem_notes', ['id'], unique=False)
    op.create_index(op.f('ix_problem_notes_problem_id'), 'problem_notes', ['problem_id'], unique=True)
    op.create_table('problem_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_review_id'), 'problem_review', ['id'], unique=False)
    op.create_index(op.f('ix_problem_review_problem_id'), 'problem_review', ['problem_id'], unique=True)
    op.create_table('problem_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_solution_id'), 'problem_solution', ['id'], unique=False)
    op.create_index(op.f('ix_problem_solution_problem_id'), 'problem_solution', ['problem_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_solution_problem_id'), table_name='problem_solution')
    op.drop_index(op.f('ix_problem_solution_id'), table_name='problem_solution')
    op.drop_table('problem_solution')
    op.drop_index(op.f('ix_problem_review_problem_id'), table_name='problem_review')
    op.drop_index(op.f('ix_problem_review_id'), table_name='problem_review')
    op.drop_table('problem_review')
    op.drop_index(op.f('ix_problem_notes_problem_id'), table_name='problem_notes')
    op.drop_index(op.f('ix_problem_notes_id'), table_name='problem_notes')
    op.drop_table('problem_notes')
    op.drop_index(op.f('ix_problem_analysis_problem_id'), table_name='problem_analysis')
    op.drop_index(op.f('ix_problem_analysis_id'), table_name='problem_analysis')
    op.drop_table('problem_analysis')
    # ### end Alembic commands ###
