"""add daily_challenge

Revision ID: e2ad78b9ab84
Revises: b775b75ed879
Create Date: 2026-06-22 08:15:50.481865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ad78b9ab84'
down_revision = 'b775b75ed879'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('daily_challenge', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'daily_challenge')
    # ### end Alembic commands ###
